import { Roboto } from 'next/font/google'
import type { Metadata } from 'next'
import './globals.css'
import NavBar from '@/components/NavBar/NavBar'
import Footer from '@/components/Footer'
export const metadata: Metadata = {
  title: 'Comic Next App',
  description: 'Generated by create next app',
}
const dosis = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900', '300'],
  variable: '--font-dosis',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css"
        />
      </head>

      <body
        className={`bg-accent-content w-full min-h-screen h-full font-dosis ${dosis.variable}`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
